### ISSUE TITLE
Document that HTTPS is required and warn if it's not used

### ISSUE THREAD

**Issue by My1** [nextcloud/twofactor_u2f#21]
a common problem that I am seeing while logging in is that with chrome (and opera) you wont be going far if you are on HTTP (errorcode 2). The firefox addon allowed HTTP when I last tried but that's actually [false behavior](https://developers.yubico.com/U2F/App_ID.html)
>NOTE
Web facets must use HTTPS [...]

so it would make most sense to kick the user to HTTPS if he isnt yet.

also you should update your shots. they show an HTTP connection which as I said wont work with the U2F standard by definition.

but while we are at it, what kind of weird browser are you using, those shots certainly dont look like any browser I've seen yet

**Comment by ChristophWurst** [comment]
> a common problem that I am seeing while logging in is that with chrome (and opera) you wont be going far if you are on HTTP (errorcode 2). The firefox addon allowed HTTP when I last tried but that's actually false behavior
> 
>     NOTE
>     Web facets must use HTTPS [...]
> 
> so it would make most sense to kick the user to HTTPS if he isnt yet.

HTTPS is required, yes. However, we cannot blindly redirect to HTTPS. IMO the administrator is responsible for ensuring that browsers use a secure connection (e.g. install TLS and set up HSTS). What if HTTPS is not configured ans we redirect? Would be pretty bad to see a browser error wouldn't it?

But of course, we have to document that HTTPS is a hard requirement. I already thought about adding that to the readme *and* the app's description, so it is shown in Nextcloud's app page too.

> also you should update your shots. they show an HTTP connection which as I said wont work with the U2F standard by definition.

That can be approved.

> but while we are at it, what kind of weird browser are you using, those shots certainly dont look like any browser I've seen yet

It's Gnome's browser: https://wiki.gnome.org/Apps/Web/. I like to use it for screenshots because it looks better than FF/Chrome. It's just my personal taste, nothing "weird" about that ;-)

Thank you for your detailed feedback. There's a lot we can improve in this app and you are very welcome to help! 😉

**Comment by My1** [comment]
Well i would love to use https, but i really miss the auto redirect option owncloud had. 
Hsts is not really what i like because it can lead to lockouts

**Comment by ChristophWurst** [comment]
> Well i would love to use https, but i really miss the auto redirect option owncloud had.

Please elaborate. Which option?

> Hsts is not really what i like because it can lead to lockouts

Same here. Why would HSTS cause lockouts?

**Comment by My1** [comment]
![screenshot 93](https://cloud.githubusercontent.com/assets/6696524/21295906/5e5db9fa-c55f-11e6-85dd-29562e671267.png)
This option (yeah I know It's OC6 but I am on windows and since I modded a bit I was too lazy to update that one)
>Same here. Why would HSTS cause lockouts?
any cert problem. and the fact that HSTS doesnt have a "thanks I know, but let me in" button.
for example when I forget to renew my cert but want to do something quickly I wont be going anywhere with HSTS, with a "normal" HTTPS redirect, I can just acknowledge it and get it.

and my NC isnt a public server or anything it's pretty much just for me, so I dont need to worry about the needs of dumb users.

**Comment by ChristophWurst** [comment]
> yeah I know It's OC6 but I am on windows and since I modded a bit I was too lazy to update that one, and I like the sidebar much more than what we have now.

🙈 🙉 🙊

**Comment by gadolithium** [comment]
This requirement is really bad as it prevents using reverse proxies efficiently. My setup is such that HTTPS connexion are broken before reaching NC and finish in plain http. NC should not prevent using u2f in this case

**Comment by ChristophWurst** [comment]
> This requirement is really bad as it prevents using reverse proxies efficiently. My setup is such that HTTPS connexion are broken before reaching NC and finish in plain http. NC should not prevent using u2f in this case
> 
> BTW this is the default setup when using docker containers

Don't worry, as long as the browser is connected via HTTPS, everything's fine :-)

**Comment by gadolithium** [comment]
This is what i get when enabling the u2f device in the user's parameters :

`U2F` device registration failed (error code 2)

**Comment by ChristophWurst** [comment]
> U2F device registration failed (error code 2)
> 
> And the setup works fine with other U2F enabled web sites

Did you configure your Nextcloud properly? If you're using a reverse proxy, there are a few config options that should be set so that NC knows the outside URL. Maybe the "app id" does not match that outside URL on your instance. Ref https://developers.yubico.com/U2F/Libraries/Client_error_codes.html

Please file an issue if the error persists.

**Comment by gadolithium** [comment]
You got me debugging ;)
It turned out that the appId was not inluding the https scheme due to the reverse proxy not setting the X-Forwarded-Proto header. Maybe include a reference to that in the documentation would help others.

Thanks for the help

**Comment by My1** [comment]
@gadolithium regarding forced HTTPS, since U2f is made via Javascript anyway, HTTPS can be enforced using JS for that matter and JS can check whether a user is on HTTPS or not just regarding the user's connection. your reverseproxy wouldnt even matter in that case.

**Comment by ChristophWurst** [comment]
cc @Nibbels @zauguin maybe something you'd like to help with :-)

**Comment by Nibbels** [comment]
I guess I never would use Owncloud or Nextcloud without https.
Main reason is because I use the installation over the internet and not at home. Even at home HTTPS would be my choice. For me I don't see any good point not to use it.

When we check if HTTPS is enabled, I guess I would do this on the server. Not with JS.
I remember me checking with 
PHP: `if($_SERVER['HTTPS'] == 'on'){}`
Source: http://php.net/reserved.variables.server
They say the servers value is nonempty, if you have HTTPS enabled. On ISAPI with IIS it is "off" when you dont have HTTPS, not empty.

I'd say, if https is not enabled the plugin needs to stay enabled but has to give a nice error with a button/link to switch to https.
In case this happens before sending any credentials, that behaviour would be even better.

Maybe this is not needed on accounts with no keys enabled.

**Comment by ChristophWurst** [comment]
> I guess I would do this on the server. Not with JS.

I have to disagree here. Operators might run their nc installation behind a proxy, hence the nc installation itself doesn't *know* it's served via HTTPS. On the client side on the other hand, we do know whether we talk via an encrypted channel or not. And that's also what the browser cares about.

> I'd say, if https is not enabled the plugin needs to stay enabled but has to give a nice error with a button/link to switch to https.

I'd stick with a warning. Then users know why they fail to authenticate. How they can upgrade to a secure connection is beyond our abilities. Who knows, maybe there is no HTTPS connection available, than that button would redirect nowhere.

**Comment by My1** [comment]
the users dont nessecarily know why, I often enought got frustrated before noticing that HTTPS was off. at the very least the warning should say that HTTPS is needed for u2f

**Comment by twouters** [comment]
@ChristophWurst I just had this issue on my own instance and learned from https://github.com/nextcloud/server/blob/695696a4a636d98b108bddb72463b46d98b95bef/lib/private/AppFramework/Http/Request.php#L632 that HTTP_X_FORWARDED_PROTO can be used when using a proxy in front of the server.
Apparently the app uses getServerProtocol() to build the app url, which resulted in an "Attestation signature does not match" exception while trying to register a u2f device because it used http in stead of https.
I would suggest to verify the used protocol with getServerProtocol() (possibly in addition to a client side check).

**Comment by ChristophWurst** [comment]
@twouters I suggest to take a look at the admin documentation. If you configure your Nextcloud correctly, it *should* all work as expected. As noted before, a server-side check is tricky because Nextcloud might be accessed via HTTP over a HTTPS-aware proxy, which is fine in most cases.

Regarding the client side check, take a look at #42 – feedback/testing/review highly appreciated 😉

**Comment by twouters** [comment]
Thanks, I just wanted to point out that a server-side check will be able to show that there's a configuration issue while a client side check might not.
In my case I had to add `proxy_set_header X-Forwarded-Proto $scheme;` to my nginx configuration to make U2F work, and it was by no means obvious that this was an issue :-)

**Comment by ChristophWurst** [comment]
> In my case I had to add proxy_set_header X-Forwarded-Proto $scheme; to my nginx configuration to make U2F work, and it was by no means obvious that this was an issue :-)

All you need should be documented at https://docs.nextcloud.com/server/11/admin_manual/configuration_server/reverse_proxy_configuration.html
