### ISSUE TITLE
Prefer U2F auth instead of TOTP when both is setup

### ISSUE THREAD

**Issue by rugk** [nextcloud/twofactor_u2f#270]
### Feature Request

Use case: Secure and convenient user login
User story: I, as a user of Nextcloud with U2F and TOTP 2FA setup, want to prefer logging in with U2F, because I want a convenient login.

### What currently happens

I have to click to choose which mode I want to use. That is cumbersome and makes me sad… :cry: 

### Summary (What should happen)

U2F can be automatically triggered if a key is available. Only if I decline that, I should be able to fallback to TOTP.
(I so no use case at all of using/prefering a less convenient method like TOTP over U2F if I have both. However… okay on mobile devices possible without USB port, if your key does not have NFC.)

GitHub e.g. does it like this and the login flow is really convenient.

**Comment by rugk** [comment]
Actually I''ve noticed GitHub is doing it in an even cleverer way. They actually have both things on the same page, so you can just press your key _or_ enter the TOTP code at the same time, do whatever just works for you. That would of course be awesome UX!

**Comment by ChristophWurst** [comment]
Hey,

thanks for this feedback. I totally see your point, but IMO we cannot prefer any provider over another. In contrast to GitHub, the Nextcloud 2FA is completely modular. The server does not know anything about u2f, totp and the others.
Moreover, there are many providers that have side effects when their challenge page is shown. The notification provider sends out a notification, the signal integration sends a signal message and so on. If we showed all available providers for the current user at once, we'd trigger 2FA side effects on many channels. Obviously, GitHub which support just u2f and totp, does not have this issue because both factors are free of side effects.

**Comment by rugk** [comment]
Yeah, I admit and totally see that it may be very difficult to implement and may need adjustments in Nextcloud's login stuff itself, but well…
From a user's perspective it would just be a greater UX if this was possible. That this is hard to implement, because it is modular is a thing the user does not care about.

Some ideas I can think of, without knowing Nextcloud's implementation:
* maybe we need some kind of priority for each 2FA provider, so it can prefer one after the other
* maybe we can define compatibility to other providers, or a "saveTrigger", so Nextcloud knows it is save to trigger this method without bad effects.
* then we maybe just prefer the 2fa module with the highest priority and then only show a button/link for other other methods, the user can click on and thus "fallback" to another method.

**Comment by slawa-dev** [comment]
@ChristophWurst 
Another solution would be to add a setting to select a default provider if there is more than one.
In the challenge page you can have an option to change to another provider.

**Comment by rugk** [comment]
This is correct, I guess https://github.com/nextcloud/server/issues/13797 tracks the idea, already.

Therefore cloding this one here.
