### ISSUE TITLE
1.0 Beta 1 ready for testing

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/twofactor_u2f#29]
Hi everyone, 

I have just uploaded a beta for v1 of this app to https://github.com/nextcloud/twofactor_u2f/releases/tag/1.0.0-beta1.

Would be cool if some people could test it on their installations and let me know if something breaks. Especially the new nfc support should be tested because I do not own a nfc compatible token.

If all goes well I will release v1 to the app store soon!

Thanks :-)
🔑 🔒 ☁️ 🚀 

cc @eddydevink @Framartin @icewind1991 @itay-grudev @LukasReschke @My1

**Comment by My1** [comment]
I dont have an NFC stick either but I am planning to get one, when/if I get it I'll test.

by the way stupid question: is making NFC support on a U2F website so much different? because you talk about "new" NFC support. as I am writing U2F on a website myself, this may be REALLY helpful for me.

**Comment by ChristophWurst** [comment]
> by the way stupid question: is making NFC support on a U2F website so much different? because you talk about "new" NFC support. as I am writing U2F on a website myself, this may be REALLY helpful for me.

I think it's only a matter of which library use. See PR https://github.com/nextcloud/twofactor_u2f/pull/24 where we updated the one used here to enable the NFC support.

**Comment by My1** [comment]
oh thanks for the info, I guess yubico updated the library a bit since I first added it.

by the way, when talking about NFC support this obviously means phones are involved. it might be helpful to use a minified js for the api because phone internet can be SLOW (for example here in germany, providers are "nice" enough to throttle down to 32 Kbit/s after a certain traffic) so 20 vs 7 KB can make a huge difference. and trust me, nothing is more frustrating than a page which relies on relatively huge js which then doesnt fully load (and in consequence any possible noscript wont help because the browser can do js.) and therefore nothing works at all (for example ajax send buttons in a forum).

**Comment by icewind1991** [comment]
Works :+1:

**Comment by eddydevink** [comment]
Tested the new version of the plugin.
- logged in with already existing u2f registration -> ok
- deregistered u2f and logged in normally -> ok
- registered u2f and logged in with u2f -> ok
- deregisterd u2f and registered u2f and let it time out with u2f device already plugged in -> ok, time out was reported by the plugin
- deregisterd u2f and registered u2f and let it time out with u2f device not plugged in -> ok, time out was reported by the plugin
- deregistered u2f and registerd u2f and immediately plugged in u2f device and activated it -> ok 

tested on
NC 11.0.0 stable
chromium 55.0.2883.75 (64-bit)
firefox 50.1.0 with U2F support addon 1.0.1

Any more things you want to be tested ?
(I don't have an nfc enabled u2f device either)
Thank you for your work on this great plugin!

**Comment by ChristophWurst** [comment]
@eddydevink thanks for your thorough testing! That should cover all this app does :-)

Let's give the translators a few days to catch up with the latest strings and I'll do the release next week.
