### ISSUE TITLE
Add release

### ISSUE THREAD

**Issue by My1** [nextcloud/twofactor_u2f#7]
as simple as it sounds, a release with all the composer stuff already resolved similar to https://github.com/ChristophWurst/twofactor_totp/releases which allows users to just place it in the extension directory and finish it.

This also allows people who dont want to have extra things on their servers (or dont trust composer for whatever reason) to use this without further problems.

**Comment by ChristophWurst** [comment]
Sure, there will be packages as soon as this is ready for production. Until then I won't create packages (or at least I don't push then onto github) because otherwise random people use it on their production systems and either a) risk their security or b) report bugs of unstable software. I hope that makes sense. I'm in the process of stabilizing the app, so there will be a package soon. Stay tuned 😉

**Comment by My1** [comment]
makes sense although I have seen ppl doing beta releases and stuff, and if someone mistakes something that has beta in the version number and clearly says pre-release (github setting) then I have no Idea how to help those.

**Comment by ChristophWurst** [comment]
Done: https://github.com/nextcloud/twofactor_u2f/releases/tag/0.0.3 😉

**Comment by ChristophWurst** [comment]
Now also available via the new app store for NC11: https://apps.nextcloud.com/apps/twofactor_u2f 😉
