### ISSUE TITLE
U2F API is being deprecated

### ISSUE THREAD

**Issue by f0zi** [nextcloud/twofactor_u2f#947]
Google Chrome is starting to deprecate the U2F API and is asking developers to use WebAuthn instead.

U2F devices are still supported through WebAuthn and existing U2F device credentials can be challenged through the WebAuthn API.

Also note that 
> Edge is (very) supportive of this deprecation/removal.

Details:
https://groups.google.com/a/chromium.org/g/blink-dev/c/xHC3AtU_65A?pli=1
https://www.yubico.com/blog/google-chrome-u2f-api-decommission-what-the-change-means-for-your-users-and-how-to-prepare/

**Comment by z3ntu** [comment]
Chromium is displaying this message in v96:

![image](https://user-images.githubusercontent.com/3768500/143783910-4851dcbc-de71-4ebe-ac6d-5e22a72381db.png)

**Comment by ChristophWurst** [comment]
> Credentials that were originally registered via the U2F API can be challenged via WebAuthn. USB security keys that are supported by the U2F API are also supported by the WebAuthn API.

so this app doesn't have to die yet, we just have to change the way we access the devices if I understand correctly.

**Comment by ChristophWurst** [comment]
we'll have to see if it makes more sense to migrate from webauthn to u2f here or invest into webauthn as full first and second authentication method as per https://github.com/nextcloud/server/issues/21215 and deprecate this app entirely

**Comment by grueneedv** [comment]
> I think having WebAuthn in U2F style as second factor still has some use especially considering external storage kinda breaks down on passwordless if it's set to use the user's credentuals.

+1 here with this (a Vote to continue this Plugin just using WebAuthn instead of U2F). We use external storage which breaks using NC WebAuthn auth.

Also when you configure WebAuthn from Nextcloud and have 2nd Factor forced for Users through the twofactor Plugin you first authenticate using WebAuthn from NC and then again through the twofactor module with the Security Key. 

Simply rely on Nextcloud only gives you not the possibility to enforce 2nd Factor and kinda breaks the ability to give TOTP as alternative 2nd Factor or backup codes.

Looking at the current implementation (version 22) of NC WebAuthn only (as already mentionend in the Issue from NC) you enter the Username and use the Security Key. This is paswordless Login but not really a second Factor in my opinion.

**Comment by My1** [comment]
> Also when you configure WebAuthn from Nextcloud and have 2nd Factor forced for Users through the twofactor Plugin you first authenticate using WebAuthn from NC and then again through the twofactor module with the Security Key.

that's because they actually have set the UV method to discouraged so basically U2F-style but without password, which is a known issue. so as long as the sticks arent enforced to use UV (pin, biometrics or whatever to verify the user is the one intended) the second factor is sadly kinda needed

**Comment by st3iny** [comment]
I'm currently working on fixing this issue. However, I might need some technical advice.

@My1 Let me ask you a question, as you seem to have some deep insights into Webauthn and U2F:

Let's pretend I implement a feature that lets users migrate to Webauthn seamlessly. Do I need access to the U2F api for that? If so, it would result in bad UX because all users would have to migrate very soon. Or is it sufficient to use only the Webauthn API for that?

If there is a need to access the U2F api for the migration, it would make more sense to completely deprecate `twofactor_u2f` and implement a new app `twofactor_webauthn`.

**Comment by My1** [comment]
the U2F API should not be needed anymore.

In Fact I have a U2F frontend which have the [yubico JS and PHP libs](https://developers.yubico.com/php-u2flib-server/Releases/) for the script and backend processing, as well as a WebAuthn side which is made with a modified copy of [lbuchs/Webauthn](https://github.com/lbuchs/WebAuthn) as a backend (as that thing was obviously not built with U2F backwards compat in mind so I fiddled around, quite a bit), with a little js which is based on his sample, and both use a PHP script I threw on for the storage management and stuff.

talking about storage here you might hit a snag, not sure if extensions on nextcloud are more or less isolated and especially if the data they make is just removed when uninstalling the extension, so maybe keep it running as twofactor_u2f but make it use webauthn.

https://my1.dev/u2f/my1.php -> register and try to login (or not) here using u2f
https://my1.dev/wa-u2f/my1.php -> use webauthn to sign in using these credentials.

you just need to know/do a few things (non-exhaustive, I only wanted it to get running, this is a sandbox, not alcatraz): 

1) the original "appID" used with U2F and throw the option parameter into the request both for signing in (because obvious) and on registration as the "excludeAppId" or whatever it was called to make sure devices dont get double-registered
2) with the yubico lib you get the keyhandle directly back as base64url, the lib I use uses binary for webauthn credentialIDs (functionally identical to the keyhandle), so in this case I need to have a base64_url decode handy, check your library and storage stuff and test well.
3) check the storage format for the public key used in both libs and convert if needed, I needed to throw on some special header (and assume we were talking ECDSA) as the lib was using a minified form of the key (which was something you actually need to find out in the first place.
4) on login, you need to handle the client data's appid marker, which should say true if the appid was used and thereby use the hash of the appid rather than the rpID's hash.
5) unrelated to U2F specifics I would recommend to use non-internal authenticators only for registration, especially because windows is a pain and doesnt tell you that you can use a USB device, you have to cancel the WinHello-based prompt to get one that allows external devices
6) also unrelated to U2F but I'd also recommend setting uv to "discouraged" so clients dont ask for a PIN, especially windows is super pedantic that it even asks the user to set a pin, even if the default preferred offers practically no security in most scenarios ([I wrote about that](https://blog.my1.dev/webauthns-userverificationpreferred-and-its-pitfalls))

and the rest should be doable by any decent webauthn implementation.

**Comment by ChristophWurst** [comment]
twofactor_webauthn already exists: https://github.com/michib/nextcloud_twofactor_webauthn

**Comment by philipreimer** [comment]
@ChristophWurst what's the plan for this now?

**Comment by ChristophWurst** [comment]
@st3iny is having a deeper look. We'll update this ticket when we know more.

**Comment by philipreimer** [comment]
That seems a bit late considering that this app is basically broken **now** for 90% of all users.

Maybe add a prominent warning to the README and the NC APP store?

**Comment by ChristophWurst** [comment]
I'm doing what's in my power to resolve this.

The warning would not be read by many nor does it help anyone who's now logged out because of this.

**Comment by st3iny** [comment]
> That seems a bit late considering that this app is basically broken now for 90% of all users.

The API hast not yet been removed. For now, it has just been disabled. If required the API can be enbled again at again at chrome://flags/#u2f-security-key-api.

**Comment by My1** [comment]
wait the API has been moved to flag-level disabled? wow.

**Comment by ChristophWurst** [comment]
yes, I've been mislead with their warning. U2F doesn't stop *after* February, it stops working with *the beginning of* February …

**Comment by My1** [comment]
ouch. if you need any help with implementing Webauthn with U2F creds hit me up and maybe I can help, I dont think I can help with specific programming since it'll likely fail on every test about coding style and whatnot but I think I might be able to assist otherwise.

**Comment by ChristophWurst** [comment]
Thank you very much @My1!

Based on the information above and what @st3iny researched in addition we can bring over u2f registration to webauthn, so they continue to work in Chrome. Other browsers, like Firefox, seem to not be effected yet. Nevertheless there might come a point where they also drop this API due to the superseded webauthn standard and it would be cumbersome to support both standards simultaneously.

The app @michib maintains seems to work nicely and it's quite familiar to the current twofactor_u2f due to their common code history.

As we understand, there are two ways we can go

1) Continue in the existing twofactor_webauthn app and add a migration there that moves over all twofactor_u2f registrations. The migration is not seamless and requires admins to read app readme/description or any other warning that we place somewhere else. I think ticket https://github.com/michib/nextcloud_twofactor_webauthn/issues/6 was meant to tackle this.
2) Replace the internals of this app to use webauthn instead of u2f, while keeping the app name/ID. Practically that would mean we'd possibly borrow back some code from @michib into this app. The migration would be transparent for the admin. The downside is that we'd have two apps with more or less the same code.

I will have to clarify internally. Nextcloud Gmbh also supports this app for customers. On that note, if you are a customer please drop us a ticket in the support system so we know you are affected.

I'm sorry for any inconveniences caused.

**Comment by klslowik** [comment]
Two-Factor U2F doesn't work with new Chrome version

https://www.yubico.com/blog/google-chrome-u2f-api-decommission-what-the-change-means-for-your-users-and-how-to-prepare/

**Comment by My1** [comment]
@klslowik we know

**Comment by ChristophWurst** [comment]
You can follow our progress of the U2F to WebAuthn migration at https://github.com/nextcloud/twofactor_webauthn/issues/110. So far it is looking good. We'll be able to release some pre-releases for testing soon. I'll let you know.

**Comment by ChristophWurst** [comment]
Please see https://github.com/nextcloud/twofactor_webauthn#migration-from-two-factor-u2f. You can now migrate to WebAuthn relatively easily.

If you have a tiny instance (for yourself) without CLI access then you will have to disable the old U2F device manually before you disable the app and register the WebAuthn device like a new device. I hope this trade-off is okay.

We'll update this app to include a final warning about the state and point over to the new kid on the block.

**Comment by z3ntu** [comment]
Migration worked flawlessly on my personal instance, thanks for making this work!

Also maybe worth adding that installing the app "Two-Factor WebAuthn" (obviously) needs to be done before attempting the migration.

**Comment by Marvo2011** [comment]
> https://github.com/nextcloud/twofactor_webauthn#migration-from-two-factor-u2f

Many tanks, migration works fine.

**Comment by My1** [comment]
> the entries are rewritten to the new format. we can't do this in a way where we guarantee this won't time out for the raspberry pi users and their 30s max request times, so I rather to the safe path and only offer things that we tested and now that work.

couldnt one do a set of migrations that's practically guaranteed to work within the time (e.g. 10) and then just trigger a 302 or whatever to the next set which has its own timeout? or whatever, the nextcloud updater can also work over web despite not nesecarily being done in 30 sec

**Comment by ChristophWurst** [comment]
In theory, yes. Right now migrations happen synchronously in one batch, though.

**Comment by nursoda** [comment]
So the full flow to migrate from `twofactor_u2f` to `twofactor_webauthn` is (for each cloud)

```
php occ app:install twofactor_webauthn
php occ twofactor_webauthn:migrate-u2f -nvv --all
php occ app:disable twofactor_u2f
php occ twofactorauth:cleanup u2f
php occ app:remove twofactor_u2f
```

That worked fast and smooth in my NC24RC3 instances.

It displayed "Migrating devices of user XY" also for users that never hat a U2F device, but there already is an issue for that and it's cosmetics ;)

In contrast to  `twofactor_u2f`, `twofactor_webauthn` displays a button (on the 2FA login screen) and waits for the user to plug in the device and press that button. So this is one additional click for a user. Apart from that, I see no difference.

Thanks to all!

**Comment by rickgardner077** [comment]
> So the full flow to migrate from `twofactor_u2f` to `twofactor_webauthn` is (for each cloud)
> 
> ```
> php occ app:install twofactor_webauthn
> php occ twofactor_webauthn:migrate-u2f -nvv --all
> php occ app:disable twofactor_u2f
> php occ twofactorauth:cleanup u2f
> php occ app:remove twofactor_u2f
> ```
> 
> That worked fast and smooth in my NC24RC3 instances.
> 
> It displayed "Migrating devices of user XY" also for users that never hat a U2F device, but there already is an issue for that and it's cosmetics ;)
> 
> In contrast to `twofactor_u2f`, `twofactor_webauthn` displays a button (on the 2FA login screen) and waits for the user to plug in the device and press that button. So this is one additional click for a user. Apart from that, I see no difference.
> 
> Thanks to all!

Migration worked flawlessly in my personal instance for 7 users

**Comment by svenseeberg** [comment]
> So the full flow to migrate from `twofactor_u2f` to `twofactor_webauthn` is (for each cloud)
> 
> ```
> php occ app:install twofactor_webauthn
> php occ twofactor_webauthn:migrate-u2f -nvv --all
> php occ app:disable twofactor_u2f
> php occ twofactorauth:cleanup u2f
> php occ app:remove twofactor_u2f
> ```
> 
> That worked fast and smooth in my NC24RC3 instances.
> 
> It displayed "Migrating devices of user XY" also for users that never hat a U2F device, but there already is an issue for that and it's cosmetics ;)
> 
> In contrast to `twofactor_u2f`, `twofactor_webauthn` displays a button (on the 2FA login screen) and waits for the user to plug in the device and press that button. So this is one additional click for a user. Apart from that, I see no difference.
> 
> Thanks to all!

It works mostly well. We have some problems though: all devices are now registered twice. Also, users cannot delete their old U2F devices and/or register them again. I guess this is due to the migration.
